### PR TITLE
Add custom masks

### PR DESCRIPTION
**Pull request by phylor**
This adds a property `masks`, which allows to pass custom masks per country.

```js
<MaterialUiPhoneNumber
  masks={{ de: '+.. ........', fr: '+.. ... .. ..' }}
>
```

Provided values are always used. If no mask is provided for a country, the default mask in `country_data` is used. Same applies if the `masks` prop is not given at all.

Related to https://github.com/alexplumb/material-ui-phone-number/issues/122 and https://github.com/alexplumb/material-ui-phone-number/issues/48.

### CODE REVIEW

**Comment by phylor** [comment]
@justdvl Hi David! Any chance to have a look on this PR? Would help us out a lot!

**Review by david-vendel — APPROVED** [review]

**Comment by david-vendel** [comment]
Hello @phylor I'm sorry I didn't got notified about this. LGTM.

**Comment by phylor** [comment]
@justdvl No worries, thank you very much!

I'll be so bold and merge this then.

**Comment by david-vendel** [comment]
@phylor This was released, see https://www.npmjs.com/package/material-ui-phone-number-2
Let me know if there are any problems with using this repository.

**Comment by phylor** [comment]
@justdvl Perfect, thank you! Works great.

**Pull request merged**
